### ISSUE TITLE
Out of nowhere Import Error

### ISSUE THREAD

**Issue by lggwettmann** [GetStream/stream-django#92]
Hey guys, 

I did not update anything, my pipfile.lock is the same and out of nowhere I'm getting this when trying to run my local server running Django 1.10:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10f11d510>
Traceback (most recent call last):
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/stream_django/__init__.py", line 1, in <module>
    from stream_django.feed_manager import feed_manager
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/stream_django/feed_manager.py", line 1, in <module>
    from stream_django.conf import FEED_MANAGER_CLASS
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/stream_django/conf.py", line 13, in <module>
    from stream_django.managers import FeedManager
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/stream_django/managers.py", line 4, in <module>
    from stream_django.client import stream_client
  File "/Users/myname/.local/share/virtualenvs/canvas-PXToinMW/lib/python3.6/site-packages/stream_django/client.py", line 4, in <module>
    from stream_django.conf import DJANGO_MAJOR_VERSION
ImportError: cannot import name 'DJANGO_MAJOR_VERSION'
```

I tried re-installing getstream via pipenv, but same error. What can I do?

**Comment by lggwettmann** [comment]
Seemed to have been a pipfile error somehow. Sorry for bothering.
